default:
  secretkey: ${JWT_SECRET:d1bee9cccfc6b1903477e580e121a84c9df6e329e7657e2025ac3fbc7c7d3f22}
server:
  port: 9080
spring:
  application:
    name: Api-Necropolis
  datasource:
    url: jdbc:mariadb://172.16.0.3:3308/jwtspringsecurity
    password: q1w2e3r4t5
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.mariadb.jdbc.Driver