server:
  port: 9080

spring:
  application:
    name: Api-Necropolis
  datasource:
    url: jdbc:mariadb://172.16.0.3:3308/jwtspringsecurity
    password: q1w2e3r4t5
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.mariadb.jdbc.Driver